### ISSUE TITLE
As an unregistered user, I want to be able to register a user with my chosen credentials  (username, password) and choose a preferred language for the application, to leverage/use the  application which is online available to registered users.

### ISSUE THREAD

**Issue by LeoEngelberger** [sopra-fs23-group-25/Pictionary-server#1]
### development tasks

- [x] sopra-fs23-group-25/Pictionary-client#1
- [x] sopra-fs23-group-25/Pictionary-client#2
- [x] sopra-fs23-group-25/Pictionary-client#3
- [x] sopra-fs23-group-25/Pictionary-server#24
- [x] sopra-fs23-group-25/Pictionary-server#25
- [x] sopra-fs23-group-25/Pictionary-server#27
- [x] sopra-fs23-group-25/Pictionary-server#28

### acceptance criteria

- [ ] Upon successful registration, the application overview page is shown and the user automatically logged in
- [ ] Upon failure, an error is displayed and the user is redirected (back) to the register 
screen. A register error can be, that a username is already taken.
- [ ] Logged-in users can log out and log back into their registered profile.
