### ISSUE TITLE
As a guesser, I want to guess the word that the painter is painting (entry field), to get  points.

### ISSUE THREAD

**Issue by LeoEngelberger** [sopra-fs23-group-25/Pictionary-server#11]
### development tasks

- [ ] sopra-fs23-group-25/Pictionary-client#40
- [x] sopra-fs23-group-25/Pictionary-client#41
- [x] sopra-fs23-group-25/Pictionary-server#86
- [x] sopra-fs23-group-25/Pictionary-server#87
- [x] sopra-fs23-group-25/Pictionary-server#88

### acceptance criteria

- [ ] Only the guessers can see an entry box to submit a guess for the word that the painter is painting.
- [ ] Guessers can submit answers which are saved automatically.
- [ ] Guessers can only see their own submission.
- [ ] Submissions are validated at the end of the round.
