### ISSUE TITLE
As a player (painter & guesser), I want to see a running timer with time left for this  round as well as the number of rounds left.

### ISSUE THREAD

**Issue by LeoEngelberger** [sopra-fs23-group-25/Pictionary-server#14]
### development tasks

- [x] sopra-fs23-group-25/Pictionary-client#48
- [x] sopra-fs23-group-25/Pictionary-client#49
- [x] sopra-fs23-group-25/Pictionary-client#50
- [x] sopra-fs23-group-25/Pictionary-server#101
- [x] sopra-fs23-group-25/Pictionary-client#74

### acceptance criteria

- [x] Display a timer/countdown, which displays the time left in the current round
- [x] Display current round-number and number of rounds left.
- [x] The timer gets reset/restarted after every round.
