### ISSUE TITLE
As a player, I want to see the result of the game at the end of the game (ranking, total  points, total times).

### ISSUE THREAD

**Issue by LeoEngelberger** [sopra-fs23-group-25/Pictionary-server#15]
### development tasks

- [x] sopra-fs23-group-25/Pictionary-client#51
- [x] sopra-fs23-group-25/Pictionary-client#53
- [x] sopra-fs23-group-25/Pictionary-server#105
- [x] sopra-fs23-group-25/Pictionary-server#106
- [x] #163
- [x] #196

### acceptance criteria

- [x] The winning player is shown to all participants of a game. 
- [x] All players, their scores, points achieved, total points is  shown to all players. These are ordered by number of total points.
- [x] By clicking on an “exit” button, the user is redirected to the lobby overview.
