### ISSUE TITLE
As a guesser I want to submit a guess in my preferred language, and have it translated. At the end of the game, I also want to see the correct answer in my preferred language.

### ISSUE THREAD

**Issue by LeoEngelberger** [sopra-fs23-group-25/Pictionary-server#16]
### development tasks

- [x] sopra-fs23-group-25/Pictionary-server#107
- [x] sopra-fs23-group-25/Pictionary-server#108
- [x] sopra-fs23-group-25/Pictionary-server#109
- [x] sopra-fs23-group-25/Pictionary-client#54
- [x] sopra-fs23-group-25/Pictionary-client#55
- [x] #162 
- [x] #167
- [x] #169
### acceptance criteria

- [ ] Using Google Translate API, a user’s guess is translated into their preferred language, before being compared to the word being drawn.
- [ ] At the end of a round, the guesses from all players are then shown in a guesser’s preferred language.
