### ISSUE TITLE
As a painter I want to read the word, I’m supposed to paint, in my preferred language.

### ISSUE THREAD

**Issue by LeoEngelberger** [sopra-fs23-group-25/Pictionary-server#17]
### development tasks

- [ ] sopra-fs23-group-25/Pictionary-server#112
- [x] sopra-fs23-group-25/Pictionary-server#113
- [x] sopra-fs23-group-25/Pictionary-server#114
- [x] sopra-fs23-group-25/Pictionary-client#56
- [x] #171
- [x] #179

### acceptance criteria

- [x] Using the Google Translate API, the word a painter is supposed to paint, is translated into the language they set as their preferred one. Once translated, the word is then shown to the painter.
- [x] At the end of a round, the guesses from all players are then shown in a painter’s preferred language.
