### ISSUE TITLE
As a logged-in user, i want to see all pages translated in my prefered language.

### ISSUE THREAD

**Issue by nczala** [sopra-fs23-group-25/Pictionary-server#172]
### development tasks

- [x] sopra-fs23-group-25/Pictionary-client#68
- [x] sopra-fs23-group-25/Pictionary-client#69
- [x] sopra-fs23-group-25/Pictionary-client#70
- [x] sopra-fs23-group-25/Pictionary-server#176
- [x] #178

### acceptance criteria

- [x] When a User is logged in, the User can see all pages translated in their preferred language
