### ISSUE TITLE
As a player, I want to leave the game without interrupting the other players.

### ISSUE THREAD

**Issue by LeoEngelberger** [sopra-fs23-group-25/Pictionary-server#18]
### development tasks

- [x] sopra-fs23-group-25/Pictionary-server#47
- [x] sopra-fs23-group-25/Pictionary-server#182
- [x] sopra-fs23-group-25/Pictionary-server#183
- [x] sopra-fs23-group-25/Pictionary-server#184
- [x] sopra-fs23-group-25/Pictionary-server#185
- [x] sopra-fs23-group-25/Pictionary-client#76
- [x] sopra-fs23-group-25/Pictionary-client#78

### acceptance criteria

- [ ] When a player clicks on the “exit” button, he leaves the game, but all the other participants can continue playing.
- [ ] Other Players get notified that a player left.
- [x] The scores of the player, who left, are kept, and they still show up in the leader board.
