### ISSUE TITLE
 As a registered user, I want to be able to login with my credentials (username,  password) to leverage/use the application which is online available to registered users.

### ISSUE THREAD

**Issue by LeoEngelberger** [sopra-fs23-group-25/Pictionary-server#2]
### development tasks

- [x] sopra-fs23-group-25/Pictionary-client#4
- [x] sopra-fs23-group-25/Pictionary-client#5
- [x] sopra-fs23-group-25/Pictionary-client#15
- [x] sopra-fs23-group-25/Pictionary-server#31
- [x] sopra-fs23-group-25/Pictionary-server#33

### acceptance criteria

- [ ] Upon successful login, the application overview page is shown, and the user 
automatically logged in.
- [ ] Upon failure, an error is displayed, and the user is redirected (back) to the login 
screen. A login error is that either the username or password is wrong.
- [ ] Logged-in users can log out and log back into their registered profile.
