### ISSUE TITLE
As a user I want the turn to end, once everyone has submitted their guess, such that I don't have to wait.

### ISSUE THREAD

**Issue by jo-ana-c** [sopra-fs23-group-25/Pictionary-server#203]
- [x] sopra-fs23-group-25/Pictionary-server#206
- [x] sopra-fs23-group-25/Pictionary-server#205
- [x] sopra-fs23-group-25/Pictionary-client#79
