### ISSUE TITLE
As a developer I want to be able to understand the source code in order to extend the application.

### ISSUE THREAD

**Issue by jo-ana-c** [sopra-fs23-group-25/Pictionary-server#211]
- [x] sopra-fs23-group-25/Pictionary-server#212
- [x] #217
- [x] sopra-fs23-group-25/Pictionary-server#213
- [x] sopra-fs23-group-25/Pictionary-server#215

### acceptance criteria

- [x] There is a test for each task.
- [x] Line coverage >= 75%.
- [x] There is an assertion in each test.
