### ISSUE TITLE
As a player, I want that the turn is terminated early, when the current Painter is not painting, such that I don't have to wait for an inactive player.

### ISSUE THREAD

**Issue by nczala** [sopra-fs23-group-25/Pictionary-server#226]
### development tasks
- [x] sopra-fs23-group-25/Pictionary-client#84
- [x] sopra-fs23-group-25/Pictionary-client#85
- [x] sopra-fs23-group-25/Pictionary-client#86

### acceptance criteria

- [x] When a player (painter) is not painting on the board, the turn is finished earlier.
- [x] The players can see, why the turn was finished, before seeing the turn-result.
