### ISSUE TITLE
As a Painter, I want to be able to clear the whole Painting from the drawing board or use an Eraser, to be able to correct what I have painted so far..

### ISSUE THREAD

**Issue by nczala** [sopra-fs23-group-25/Pictionary-server#236]
### development tasks

- [ ] sopra-fs23-group-25/Pictionary-client#92
- [ ] sopra-fs23-group-25/Pictionary-client#91
- [ ] sopra-fs23-group-25/Pictionary-client#90

### acceptance criteria

 - [x] The painter can clear the whole Drawing board when clicking a button, and the drawing board is cleared on all other players in real time.
 - [x] The painter can use an eraser, with which the painter can correct older lines on the drawing boards, and all other players receive the changes in real time.
 - [x] The painters cursor is changing to an erasor, when the eraser is activated.
