### ISSUE TITLE
As a registered user, I want to see the game rules/description, such that I can understand how the game works.

### ISSUE THREAD

**Issue by nczala** [sopra-fs23-group-25/Pictionary-server#255]
### development tasks

- [x] sopra-fs23-group-25/Pictionary-client#100
- [x] sopra-fs23-group-25/Pictionary-client#101
- [x] sopra-fs23-group-25/Pictionary-client#102
- [x] sopra-fs23-group-25/Pictionary-client#103
### acceptance criteria

- [x] A registered user can navigate from to the lobbyoverview page to the rules page by clicking on a rules-icon.
- [x] The rules are shown in a users preferred language.
- [x] A user can navigate back to the lobbyoverview by clicking on a "back" button
