### ISSUE TITLE
As a logged-in user, I want to create a lobby/room, to set up a game and become a  game-host.

### ISSUE THREAD

**Issue by LeoEngelberger** [sopra-fs23-group-25/Pictionary-server#4]
### development tasks

- [ ] sopra-fs23-group-25/Pictionary-client#20
- [ ] sopra-fs23-group-25/Pictionary-client#21
- [ ] sopra-fs23-group-25/Pictionary-client#22
- [ ] sopra-fs23-group-25/Pictionary-server#58
- [ ] sopra-fs23-group-25/Pictionary-server#59

### acceptance criteria

- [x] In the lobby overview the user can initiate a new lobby by clicking on a “create new 
lobby” button and then being redirected to the lobby setting page.
- [x] The user can save the lobby settings and the lobby is created.
- [x] The user who created the lobby automatically becomes the game-host.
- [x] The game-host can start the game by clicking on a “start game” button.
- [x] The game-host can close the lobby at any time by clicking on a “close lobby” button 
and is redirected to the lobby overview.
