### ISSUE TITLE
As a game-host, I want to set the settings of the game (time, rounds, nr of players).

### ISSUE THREAD

**Issue by LeoEngelberger** [sopra-fs23-group-25/Pictionary-server#5]
### development tasks

- [x] sopra-fs23-group-25/Pictionary-client#24
- [x] sopra-fs23-group-25/Pictionary-client#23
- [x] sopra-fs23-group-25/Pictionary-server#62
- [x] sopra-fs23-group-25/Pictionary-client#25
- [x] sopra-fs23-group-25/Pictionary-client#26
- [x] sopra-fs23-group-25/Pictionary-server#64
- [x] sopra-fs23-group-25/Pictionary-client#71

### acceptance criteria

 - [x] The game-host can modify the default settings: time per round, nr of rounds, nr of 
players.
 - [x] The game-host can save his modifications with a “save settings” button.
 - [x] By clicking on a “finalize lobby” button, the lobby is created, set online and shows up 
in the lobby overview page for other players to see.
 - [x] The game-host is redirected to the game page of this lobby.
 - [x] By clicking on a “back to lobby overview” button, the settings are not saved, the 
lobby is closed and the game host is redirected to the lobby overview.
