### ISSUE TITLE
As a logged-in user, I want to see all lobbies and join a lobby/room, to join a game.

### ISSUE THREAD

**Issue by LeoEngelberger** [sopra-fs23-group-25/Pictionary-server#6]
### development tasks

- [x] sopra-fs23-group-25/Pictionary-client#14
- [x] sopra-fs23-group-25/Pictionary-server#35
- [x] sopra-fs23-group-25/Pictionary-client#13
- [x] sopra-fs23-group-25/Pictionary-client#12
- [x] sopra-fs23-group-25/Pictionary-server#38
- [x] sopra-fs23-group-25/Pictionary-server#177
- [x] sopra-fs23-group-25/Pictionary-client#73

### acceptance criteria

- [x] In the lobby overview the user can see all available lobbies.
- [x] Available lobbies are all lobbies that are created but haven’t started yet.
- [x] By clicking on a lobby, the user can join a lobby and is redirected to the game page of 
this lobby.
- [x] The names of joined users are visible on the game page.
