### ISSUE TITLE
As a game-host, I want to start a game, to begin with the first round of the game.

### ISSUE THREAD

**Issue by LeoEngelberger** [sopra-fs23-group-25/Pictionary-server#7]
### development tasks

- [x] sopra-fs23-group-25/Pictionary-client#27
- [x] sopra-fs23-group-25/Pictionary-server#67
- [x] sopra-fs23-group-25/Pictionary-server#68
- [x] sopra-fs23-group-25/Pictionary-server#69
- [x] sopra-fs23-group-25/Pictionary-client#30
- [x] sopra-fs23-group-25/Pictionary-client#29
- [x] #161
### acceptance  #criteria

- [x] A game can only be started once there are at least 2 players in the lobby.
- [x] Only the game-host can start the game by clicking on a “start game” button only 
visible to the game-host (on the game page for the lobby).
- [x] As soon as the “start game” button is pressed, the game begins for all players in the lobby
