### ISSUE TITLE
Before every round, the roles are set (painter/guessers).

### ISSUE THREAD

**Issue by LeoEngelberger** [sopra-fs23-group-25/Pictionary-server#8]
### development tasks

- [ ] sopra-fs23-group-25/Pictionary-server#73
- [ ] sopra-fs23-group-25/Pictionary-client#31
- [ ] sopra-fs23-group-25/Pictionary-client#32

### acceptance criteria

- [ ] When the game begins, the game host is automatically the first painter.
- [ ] All other players start as guessers.
- [ ] After every round a new player becomes the painter.
- [ ] At the end all players have been a painter the same number of times.
