### ISSUE TITLE
As a painter, I want to paint (the assigned word) on the drawing board.

### ISSUE THREAD

**Issue by LeoEngelberger** [sopra-fs23-group-25/Pictionary-server#9]
### development tasks

- [x] sopra-fs23-group-25/Pictionary-client#33
- [x] sopra-fs23-group-25/Pictionary-client#34
- [x] sopra-fs23-group-25/Pictionary-client#36
- [x] sopra-fs23-group-25/Pictionary-client#37
- [x] sopra-fs23-group-25/Pictionary-client#38
- [x] sopra-fs23-group-25/Pictionary-server#83
- [x] sopra-fs23-group-25/Pictionary-client#75

### acceptance criteria

- [x] Drawing board is seen only in the active game page of the lobby.
- [x] Painters can paint on a canvas with tools from a toolbar.
- [x] Only the painter can see the toolbar and paint on the drawing board.
- [x] The other players can see only the drawing board.
